/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PreviewShweHotpotRouteImport } from './routes/preview.shwe-hotpot'
import { Route as RShweHotpotTableTableRouteImport } from './routes/r.shwe-hotpot.table.$table'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewShweHotpotRoute = PreviewShweHotpotRouteImport.update({
  id: '/preview/shwe-hotpot',
  path: '/preview/shwe-hotpot',
  getParentRoute: () => rootRouteImport,
} as any)
const RShweHotpotTableTableRoute = RShweHotpotTableTableRouteImport.update({
  id: '/r/shwe-hotpot/table/$table',
  path: '/r/shwe-hotpot/table/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consult': typeof ConsultRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/preview/shwe-hotpot': typeof PreviewShweHotpotRoute
  '/r/shwe-hotpot/table/$table': typeof RShweHotpotTableTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consult': typeof ConsultRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/preview/shwe-hotpot': typeof PreviewShweHotpotRoute
  '/r/shwe-hotpot/table/$table': typeof RShweHotpotTableTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consult': typeof ConsultRoute
  '/owner': typeof OwnerRoute
  '/setup': typeof SetupRoute
  '/preview/shwe-hotpot': typeof PreviewShweHotpotRoute
  '/r/shwe-hotpot/table/$table': typeof RShweHotpotTableTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consult'
    | '/owner'
    | '/setup'
    | '/preview/shwe-hotpot'
    | '/r/shwe-hotpot/table/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consult'
    | '/owner'
    | '/setup'
    | '/preview/shwe-hotpot'
    | '/r/shwe-hotpot/table/$table'
  id:
    | '__root__'
    | '/'
    | '/consult'
    | '/owner'
    | '/setup'
    | '/preview/shwe-hotpot'
    | '/r/shwe-hotpot/table/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultRoute: typeof ConsultRoute
  OwnerRoute: typeof OwnerRoute
  SetupRoute: typeof SetupRoute
  PreviewShweHotpotRoute: typeof PreviewShweHotpotRoute
  RShweHotpotTableTableRoute: typeof RShweHotpotTableTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/shwe-hotpot': {
      id: '/preview/shwe-hotpot'
      path: '/preview/shwe-hotpot'
      fullPath: '/preview/shwe-hotpot'
      preLoaderRoute: typeof PreviewShweHotpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/shwe-hotpot/table/$table': {
      id: '/r/shwe-hotpot/table/$table'
      path: '/r/shwe-hotpot/table/$table'
      fullPath: '/r/shwe-hotpot/table/$table'
      preLoaderRoute: typeof RShweHotpotTableTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultRoute: ConsultRoute,
  OwnerRoute: OwnerRoute,
  SetupRoute: SetupRoute,
  PreviewShweHotpotRoute: PreviewShweHotpotRoute,
  RShweHotpotTableTableRoute: RShweHotpotTableTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
