// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqgoheoyuibmqusbezvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxZ29oZW95dWlibXF1c2JlenZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyMzI4MTEsImV4cCI6MjEwMjgwODgxMX0.Q7OTI3pOLSJgMQk3Wiz6DbDPJ_2Jkc42xJfljRC2WNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});